"""add company to users

Revision ID: d1e0e2c2bd29
Revises: 1a1ac490ea2c
Create Date: 2026-03-12 04:16:39.906159

"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = 'd1e0e2c2bd29'
down_revision: Union[str, None] = '1a1ac490ea2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('company', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'company')
    # ### end Alembic commands ###
